"""Sale receipt rendering — on-screen text and printable PDF.

The receipt is built from the ``SaleItem`` snapshots, so reprinting a receipt
years later still shows exactly what was charged, not today's product data.
Page height is sized to the content so an 80 mm thermal roll gets one clean
cut instead of a trailing blank page.
"""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import HRFlowable, Image, Paragraph, SimpleDocTemplate, Spacer, Table

from core.dates import format_datetime
from core.exceptions import FileError
from core.logger import get_logger
from core.money import format_rate, to_money
from core.paths import resolve_image_path
from models import Sale
from services.settings_service import SettingsSnapshot

logger = get_logger("reports.receipt")

PAGE_WIDTH = 80 * mm
MARGIN = 6 * mm
#: reportlab's Frame pads 6pt on every side, so the usable width is narrower
#: than the page margins alone suggest.
FRAME_PADDING = 6
CONTENT_WIDTH = PAGE_WIDTH - (2 * MARGIN) - (2 * FRAME_PADDING)

THANK_YOU = "Thank you for shopping with us."
FOOTER = "Generated by VEYRA"


def _amount(value) -> str:
    """Bare amount — the column is already headed 'KSh' on a narrow roll."""
    return f"{to_money(value):,.2f}"


def render_receipt_text(sale: Sale, settings: SettingsSnapshot) -> str:
    """Plain-text receipt for the on-screen preview (monospaced widget)."""
    lines: list[str] = []
    lines.append(settings.business_name.center(40))
    for detail in (settings.address, settings.phone, settings.email):
        if detail:
            lines.append(str(detail).center(40))
    lines.append("-" * 40)
    lines.append(f"{sale.invoice_number:<20}{format_datetime(sale.sale_date):>20}")
    lines.append("-" * 40)
    lines.append(f"{'Item':<22}{'Qty':>5}{'Amount (KSh)':>13}")

    for item in sale.items:
        lines.append(
            f"{item.product_name_snapshot[:21]:<22}"
            f"{item.quantity:>5}{_amount(item.line_total):>13}"
        )
    lines.append("-" * 40)
    lines.append(f"{'Subtotal':<27}{_amount(sale.subtotal):>13}")
    if to_money(sale.discount):
        lines.append(f"{'Discount':<27}{'-' + _amount(sale.discount):>13}")
    if to_money(sale.vat_amount):
        label = f"VAT ({format_rate(sale.vat_rate_snapshot)}%)"
        lines.append(f"{label:<27}{_amount(sale.vat_amount):>13}")
    lines.append(f"{'TOTAL':<27}{_amount(sale.total):>13}")
    lines.append(f"{'Items / units':<27}{sale.item_count:>4}/{sale.total_quantity:<8}")
    lines.append("-" * 40)
    if sale.note:
        lines.append(str(sale.note).center(40))
    lines.append(THANK_YOU.center(40))
    lines.append(FOOTER.center(40))
    return "\n".join(lines)


# ------------------------------------------------------------------- pdf styles


def _styles():
    return {
        "business": ParagraphStyle(
            "business", fontName="Helvetica-Bold", fontSize=12, leading=14, alignment=TA_CENTER
        ),
        "meta": ParagraphStyle(
            "meta", fontName="Helvetica", fontSize=7.5, leading=9.5, alignment=TA_CENTER,
            textColor=colors.HexColor("#374151"),
        ),
        "heading": ParagraphStyle(
            "heading", fontName="Helvetica-Bold", fontSize=9, leading=11, alignment=TA_CENTER
        ),
        "label": ParagraphStyle("label", fontName="Helvetica", fontSize=8, leading=10),
        "item": ParagraphStyle("item", fontName="Helvetica", fontSize=8, leading=10),
        "right": ParagraphStyle(
            "right", fontName="Helvetica", fontSize=8, leading=10, alignment=TA_RIGHT
        ),
        "center": ParagraphStyle(
            "center", fontName="Helvetica", fontSize=7.5, leading=9.5, alignment=TA_CENTER,
            textColor=colors.HexColor("#374151"),
        ),
        "total": ParagraphStyle(
            "total", fontName="Helvetica-Bold", fontSize=10, leading=12, alignment=TA_RIGHT
        ),
        "total_label": ParagraphStyle(
            "total_label", fontName="Helvetica-Bold", fontSize=10, leading=12
        ),
    }


def _logo(stored_reference: str | None):
    source = resolve_image_path(stored_reference)
    if source is None:
        return None
    try:
        image = Image(str(source))
    except Exception:  # noqa: BLE001 - a broken logo must not block the receipt
        logger.warning("Receipt logo %s could not be embedded", source)
        return None
    ratio = min(30 * mm / image.imageWidth, 12 * mm / image.imageHeight)
    image.drawWidth = image.imageWidth * ratio
    image.drawHeight = image.imageHeight * ratio
    image.hAlign = "CENTER"
    return image


def _items_table(sale: Sale, styles) -> Table:
    rows = [[
        Paragraph("<b>Item</b>", styles["item"]),
        Paragraph("<b>Qty</b>", styles["right"]),
        Paragraph("<b>Price</b>", styles["right"]),
        Paragraph("<b>Amount</b>", styles["right"]),
    ]]
    for item in sale.items:
        name = Paragraph(
            f"{escape(item.product_name_snapshot)}"
            f'<font size="6.8" color="#6B7280"><br/>'
            f"{escape(item.product_code_snapshot)}</font>",
            styles["item"],
        )
        rows.append([
            name,
            Paragraph(f"{item.quantity} {escape(item.unit_snapshot)}", styles["right"]),
            Paragraph(_amount(item.unit_price), styles["right"]),
            Paragraph(_amount(item.line_total), styles["right"]),
        ])

    table = Table(
        rows,
        colWidths=[CONTENT_WIDTH * 0.46, CONTENT_WIDTH * 0.15, CONTENT_WIDTH * 0.17,
                   CONTENT_WIDTH * 0.22],
        hAlign="LEFT",
    )
    table.setStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#9CA3AF")),
    ])
    return table


def _totals_table(sale: Sale, styles) -> Table:
    rows = [
        [Paragraph("Subtotal", styles["label"]),
         Paragraph(_amount(sale.subtotal), styles["right"])],
    ]
    if to_money(sale.discount):
        rows.append([
            Paragraph("Discount", styles["label"]),
            Paragraph(f"- {_amount(sale.discount)}", styles["right"]),
        ])
    if to_money(sale.vat_amount):
        rows.append([
            Paragraph(f"VAT ({format_rate(sale.vat_rate_snapshot)}%)", styles["label"]),
            Paragraph(_amount(sale.vat_amount), styles["right"]),
        ])
    rows.append([
        Paragraph("TOTAL (KSh)", styles["total_label"]),
        Paragraph(_amount(sale.total), styles["total"]),
    ])
    table = Table(rows, colWidths=[CONTENT_WIDTH * 0.6, CONTENT_WIDTH * 0.4], hAlign="LEFT")
    table.setStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
        ("LINEABOVE", (0, -1), (-1, -1), 0.7, colors.HexColor("#111827")),
    ])
    return table


def _story(sale: Sale, settings: SettingsSnapshot) -> list:
    styles = _styles()
    story: list = []

    logo = _logo(settings.logo_image)
    if logo is not None:
        story += [logo, Spacer(1, 2 * mm)]
    story.append(Paragraph(escape(settings.business_name), styles["business"]))
    for detail in (settings.address, settings.phone, settings.email):
        if detail:
            story.append(Paragraph(escape(str(detail)), styles["meta"]))

    story += [Spacer(1, 2 * mm), Paragraph("SALES RECEIPT", styles["heading"])]
    story.append(
        Paragraph(f"{escape(sale.invoice_number)} &nbsp;|&nbsp; "
                  f"{format_datetime(sale.sale_date)}",
                  styles["meta"])
    )
    story += [
        Spacer(1, 1.5 * mm),
        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#9CA3AF")),
        Spacer(1, 1.5 * mm),
        _items_table(sale, styles),
        Spacer(1, 1.5 * mm),
        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#9CA3AF")),
        Spacer(1, 1.5 * mm),
        _totals_table(sale, styles),
    ]

    if sale.note:
        story += [Spacer(1, 2 * mm), Paragraph(escape(str(sale.note)), styles["center"])]

    story += [
        Spacer(1, 3 * mm),
        Paragraph(THANK_YOU, styles["center"]),
        Spacer(1, 1 * mm),
        Paragraph(FOOTER, styles["center"]),
    ]
    return story


def export_receipt_pdf(
    sale: Sale,
    destination: Path | str,
    *,
    settings: SettingsSnapshot,
) -> Path:
    """Write a single-roll receipt for ``sale`` and return the path written."""
    path = Path(destination)
    story = _story(sale, settings)

    # Measure at a generous height, then set the page to exactly what fits.
    # A very long receipt is capped at A4 height so it paginates cleanly
    # instead of producing one enormous strip plus a near-empty second page.
    height = (MARGIN * 2) + (FRAME_PADDING * 2)
    for flowable in story:
        _width, used = flowable.wrap(CONTENT_WIDTH, 1000 * mm)
        height += used
    page_height = min(max(height + 2 * mm, 60 * mm), 297 * mm)

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        document = SimpleDocTemplate(
            str(path),
            pagesize=(PAGE_WIDTH, page_height),
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN,
            bottomMargin=MARGIN,
            title=f"{sale.invoice_number} - {settings.business_name}",
            author=settings.business_name,
        )
        document.build(story)
    except OSError as exc:
        logger.error("Receipt PDF to %s failed: %s", path, exc)
        raise FileError("The receipt could not be saved.", detail=repr(exc)) from exc
    except Exception as exc:  # noqa: BLE001 - reportlab internals surface as FileError
        logger.error("Receipt PDF to %s failed", path, exc_info=exc)
        raise FileError("The receipt could not be generated.", detail=repr(exc)) from exc

    logger.info("Receipt PDF for %s -> %s", sale.invoice_number, path)
    return path
